module.exports = [
  "adobe bread",
  "afghan bread",
  "agathabrot",
  "aloo paratha",
  "altamura",
  "amish friendship bread",
  "anadama bread",
  "arepa",
  "baati",
  "babka (bread)",
  "baguette",
  "bakarkhani",
  "baking",
  "balep korkun",
  "ballon",
  "bammy",
  "banana bread",
  "bannock",
  "bannock",
  "bannock",
  "baozi",
  "barbari bread",
  "barm",
  "basler brot",
  "bataw",
  "bazlama",
  "beaten biscuit",
  "benne dose",
  "bhakri",
  "bhakri",
  "bhatoora",
  "bhatoora",
  "bhatoora",
  "biga",
  "biga",
  "bindaetteok",
  "bing",
  "bing",
  "biscuit",
  "biscuit",
  "bolani",
  "bolillo",
  "bonhomme de saint nicolas",
  "boule",
  "bramboráček",
  "brascidèla",
  "bread pan",
  "brioche",
  "brown bread",
  "bröötis",
  "bulkie roll",
  "burebrot",
  "buñuelo",
  "bürli",
  "casabe",
  "cemita",
  "cha siu baau",
  "chapati",
  "chapati",
  "chapati",
  "chapati",
  "churro",
  "ciabatta",
  "cochinito de piloncillo",
  "cocol",
  "cong you bing",
  "coppia ferrarese",
  "corn tortilla",
  "cornbread",
  "crescentina modenese",
  "crispbread",
  "croissant",
  "croutons",
  "cuban bread",
  "cuchaule",
  "cōng yóu bǐng",
  "dalieba",
  "dosa",
  "eish merahrah",
  "faluche",
  "farinata",
  "farl",
  "ficelle",
  "filone",
  "flammkuchen",
  "flatbread",
  "flatbrød",
  "flatkaka",
  "focaccia",
  "focaccia",
  "fougasse",
  "french toast",
  "frybread",
  "frybread",
  "garibaldi biscuit",
  "gnocco fritto",
  "graham bread",
  "grissini",
  "grittibänz",
  "gözleme",
  "hard dough bread",
  "hoggan",
  "hot water corn bread",
  "huamo",
  "hujiao bing",
  "hushpuppy",
  "idli",
  "injera",
  "injera",
  "jianbing",
  "johnnycake",
  "jolada rotti",
  "jolada rotti",
  "kaak",
  "kaak",
  "kattama",
  "kerala porotta",
  "khachapuri",
  "khakhra",
  "khebz",
  "khubz",
  "khubz",
  "kompyang",
  "kulcha",
  "kulcha",
  "lahoh",
  "lahoh",
  "lame",
  "langbrot",
  "laobing",
  "laobing",
  "lavash",
  "lefse",
  "luchi",
  "luchi",
  "lángos",
  "makki di roti",
  "makki di roti",
  "malooga",
  "manda pitha",
  "mandarin roll",
  "mantou",
  "markook",
  "matzo",
  "mekitsa",
  "michetta",
  "motschellen",
  "muffin",
  "muffuletta",
  "muffuletta",
  "multigrain bread",
  "mung bean dosa",
  "münstertaler brot",
  "naan",
  "naan",
  "naan",
  "naan",
  "neer dosa",
  "ngome",
  "obi non",
  "opłatek",
  "pain brié",
  "pain d'épices",
  "pain de campagne",
  "pain de mie",
  "pain de seigle",
  "pajeon",
  "pambazo",
  "pan de muerto",
  "pan dulce",
  "pancake",
  "pandoro",
  "pane carasau",
  "pane carasau",
  "pane sciocco",
  "pane ticinese",
  "panettone",
  "papadum",
  "papadum",
  "papadum",
  "paratha",
  "paratha",
  "paratha",
  "paratha",
  "parker house roll",
  "parotta",
  "parotta",
  "pashti",
  "pathiri",
  "pathiri",
  "paun jauer",
  "peel",
  "penia",
  "pepperoni roll",
  "petits pains",
  "phitti",
  "phitti",
  "piadina",
  "piadina",
  "pita",
  "pita",
  "pitha",
  "pitta",
  "pizza",
  "pletzel",
  "podpłomyk",
  "popover",
  "pullman loaf",
  "puran poli",
  "puran poli",
  "puri",
  "puri",
  "puri",
  "puttu",
  "qistibi",
  "quick",
  "qutab",
  "ramazan pidesi",
  "rava dosa",
  "rieska",
  "rosca",
  "roti",
  "roti",
  "roti",
  "roti canai",
  "roti prata",
  "rua-brot",
  "rumali roti",
  "rumali roti",
  "rumali roti",
  "rye bread",
  "sacramental bread",
  "salt-rising bread",
  "sanchuisanda",
  "sanchuisanda",
  "sandwich bread",
  "sandwiches",
  "sangak",
  "sanna",
  "scaccia",
  "schlumbergerli",
  "sepik",
  "shaobing",
  "shaobing",
  "sheermal",
  "sheermal",
  "sheermal",
  "shelpek",
  "shengjian mantou",
  "shotis puri",
  "sloosh",
  "soboro bread",
  "soda bread",
  "somun",
  "sourdough",
  "spanischbrötli",
  "st. galler brot",
  "taboon bread",
  "taftan",
  "taftan",
  "tandoor bread",
  "taralli",
  "texas toast",
  "texas toast",
  "thalipeeth",
  "thalipeeth",
  "toast",
  "tohax",
  "tortilla de rescoldo",
  "totopo",
  "tunnbröd",
  "türggenbrot",
  "unleavened",
  "urner brot",
  "uttapam",
  "vastedda",
  "wagafi bread",
  "weggli",
  "white bread",
  "whole wheat",
  "wotou",
  "xiaolongbao",
  "yong peng bread",
  "youtazi",
  "yufka",
  "zhingyalov hats",
  "zopf",
  "zürcher brot",
  "zürcher murren",
  "de reyes",
  "panini"
];
