module.exports = [
    "acerola",
    "pomme",
    "apple",
    "apricots",
    "avocado",
    "banana",
    "blackcurrant",
    "blueberries",
    "breadfruit",
    "cantaloupe",
    "carambola",
    "cherimoya",
    "cherries",
    "clementine",
    "coconut meat",
    "cranberries",
    "custard-apple",
    "date fruit",
    "durian",
    "elderberries",
    "feijoa",
    "figs",
    "gooseberries",
    "grapefruit",
    "grapes",
    "guava",
    "honeydew melon",
    "jackfruit",
    "java-plum",
    "jujube fruit",
    "kiwifruit",
    "kumquat",
    "lemon",
    "lime",
    "longan",
    "loquat",
    "lychee",
    "mandarin",
    "mango",
    "mangosteen",
    "mulberries",
    "nectarine",
    "olives",
    "orange",
    "papaya",
    "passion fruit",
    "peaches",
    "pear",
    "persimmon japanese",
    "pineapple",
    "pitanga",
    "plantain",
    "plums",
    "pomegranate",
    "prickly pear",
    "prunes",
    "pummelo",
    "quince",
    "raspberries",
    "rhubarb",
    "rose-apple",
    "sapodilla",
    "sapote mamey",
    "soursop",
    "strawberries",
    "sugar-apple",
    "tamarind",
    "tangerine",
    "watermelon"
];

