module.exports = [
"akat amnuai",
"amphawa",
"ao luek",
"aranyaprathet",
"at samat",
"bacho",
"bamnet narong",
"ban bueng",
"ban chang",
"ban dan",
"ban dan lan hoi",
"ban dung",
"ban fang",
"ban haet",
"ban hong",
"ban kha",
"ban khai",
"ban khok",
"ban khwao",
"ban kruat",
"ban laem",
"ban lat",
"ban luang",
"ban lueam",
"ban mai chaiyaphot",
"ban mi",
"ban mo",
"ban muang",
"ban na",
"ban na doem",
"ban na san",
"ban phaeng",
"ban phaeo",
"ban phai",
"ban pho",
"ban phraek",
"ban phue",
"ban pong",
"ban rai",
"ban sang",
"ban ta khun",
"ban tak",
"ban thaen",
"ban thi",
"bang ban",
"bang bo",
"bang bua thong",
"bang kaeo",
"bang khan",
"bang khla",
"bang khonthi",
"bang klam",
"bang krathum",
"bang kruai",
"bang lamung",
"bang len",
"bang mun nak",
"bang nam priao",
"bang pa in",
"bang pahan",
"bang pakong",
"bang phae",
"bang phli",
"bang pla ma",
"bang rachan",
"bang rakam",
"bang sao thong",
"bang saphan",
"bang saphan noi",
"bang yai",
"bannang sata",
"banphot phisai",
"benchalak",
"betong",
"bo kluea",
"bo phloi",
"bo rai",
"bo thong",
"borabue",
"bua lai",
"bua yai",
"buachet",
"bueng bun",
"bueng khong long",
"bueng na rang",
"bueng sam phan",
"bueng samakkhi",
"bung khla",
"buntharik",
"cha-am",
"cha-uat",
"chae hom",
"chai badan",
"chaiyo",
"chai buri",
"chai prakan",
"chai wan",
"chaiya",
"chakkarat",
"chamni",
"chana",
"chanae",
"changhan",
"chang klang",
"chanuman",
"charoen sin",
"chat trakan",
"chatturat",
"chaturaphak phiman",
"chawang",
"chian yai",
"chiang dao",
"chiang kham",
"chiang khan",
"chiang khong",
"chiang khwan",
"chiang klang",
"chiang muan",
"chiang saen",
"chiang yuen",
"cho-airong",
"chok chai",
"chom bueng",
"chom phra",
"chon daen",
"chonnabot",
"chuen chom",
"chulabhorn",
"chum phae",
"chum phuang",
"chum saeng",
"chum ta bong",
"chumphon buri",
"chun",
"damnoen saduak",
"dan chang",
"dan khun thot",
"dan makham tia",
"dan sai",
"den chai",
"det udom",
"doem bang nang buat",
"doi lo",
"doi luang",
"doi saket",
"doi tao",
"dok khamtai",
"don chan",
"don chedi",
"don mot daeng",
"don phut",
"don sak",
"don tan",
"don tum",
"dong charoen",
"dong luang",
"erawan",
"fak tha",
"fang",
"fao rai",
"galyani vadhana",
"hang chat",
"hang dong",
"hankha",
"hat samran",
"hat yai",
"hot",
"hua hin",
"hua sai",
"hua taphan",
"huai khot",
"huai krachao",
"huai mek",
"huai phueng",
"huai rat",
"huai thalaeng",
"huai thap than",
"huai yot",
"in buri",
"kabang",
"kabin buri",
"kae dam",
"kaeng hang maeo",
"kaeng khoi",
"kaeng khro",
"kaeng krachan",
"kaeng sanam nang",
"kamalasai",
"kamphaeng saen",
"kanchanadit",
"kantang",
"kantharalak",
"kanthararom",
"kantharawichai",
"kao liao",
"kap choeng",
"kapho",
"kapoe",
"kapong",
"kaset sombun",
"kaset wisai",
"kathu",
"khaen dong",
"khai bang rachan",
"kham khuean kaeo",
"kham muang",
"kham sakaesaeng",
"kham ta kla",
"kham thale so",
"khamcha-i",
"khanom",
"khanu woralaksaburi",
"khao chaison",
"khao chakan",
"khao chamao",
"khao khitchakut",
"khao kho",
"khao phanom",
"khao saming",
"khao suan kwang",
"khao wong",
"khao yoi",
"khemarat",
"khian sa",
"khiri mat",
"khiri rat nikhom",
"khlong hat",
"khlong hoi khong",
"khlong khlung",
"khlong khuean",
"khlong lan",
"khlong luang",
"khlong thom",
"khlong yai",
"khlung",
"kho wang",
"khok charoen",
"khok pho",
"khok pho chai",
"khok samrong",
"khok si suphan",
"khok sung",
"khon buri",
"khon san",
"khon sawan",
"khong chai",
"khong chiam",
"khu mueang",
"khuan don",
"khuan kalong",
"khuan khanun",
"khuan niang",
"khueang nai",
"khukhan",
"khun han",
"khun tan",
"khun yuam",
"khura buri",
"khwao sinarin",
"klaeng",
"ko chan",
"ko chang",
"ko kha",
"ko kut",
"ko lanta",
"ko pha-ngan",
"ko samui",
"ko sichang",
"ko yao",
"kong krailat",
"kong ra",
"kosamphi nakhon",
"kosum phisai",
"kra buri",
"kranuan",
"krasae sin",
"krasang",
"krathum baen",
"krok phra",
"krong pinang",
"ku kaeo",
"kuchinarai",
"kui buri",
"kumphawapi",
"kusuman",
"kut bak",
"kut chap",
"kut chum",
"kut khaopun",
"kut rang",
"la-ngu",
"la-un",
"laem ngop",
"laem sing",
"lahan sai",
"lam luk ka",
"lam plai mat",
"lam sonthi",
"lam thamenchai",
"lam thap",
"lamae",
"lamduan",
"lan krabue",
"lan sak",
"lan saka",
"lang suan",
"lao khwan",
"lao suea kok",
"laplae",
"lat bua luang",
"lat lum kaeo",
"lat yao",
"li",
"loeng nok tha",
"lom kao",
"lom sak",
"lue amnat",
"mae ai",
"mae charim",
"mae chaem",
"mae chai",
"mae chan",
"mae fa luang",
"mae la noi",
"mae lan",
"mae lao",
"mae mo",
"mae on",
"mae phrik",
"mae poen",
"mae ramat",
"mae rim",
"mae sai",
"mae sariang",
"mae sot",
"mae suai",
"mae taeng",
"mae wang",
"mae wong",
"maha chana chai",
"maha rat",
"mai kaen",
"makham",
"mancha khiri",
"manorom",
"mayo",
"moei wadi",
"muak lek",
"muang sam sip",
"mueang amnat charoen",
"mueang ang thong",
"mueang bueng kan",
"mueang buriram",
"mueang chachoengsao",
"mueang chainat",
"mueang chaiyaphum",
"mueang chan",
"mueang chanthaburi",
"mueang chiang mai",
"mueang chiang rai",
"mueang chonburi",
"mueang chumphon",
"mueang kalasin",
"mueang kamphaeng phet",
"mueang kanchanaburi",
"mueang khon kaen",
"mueang krabi",
"mueang lampang",
"mueang lamphun",
"mueang loei",
"mueang lopburi",
"mueang mae hong son",
"mueang maha sarakham",
"mueang mukdahan",
"mueang nakhon nayok",
"mueang nakhon pathom",
"mueang nakhon phanom",
"mueang nakhon ratchasima",
"mueang nakhon sawan",
"mueang nakhon si thammarat",
"mueang nan",
"mueang narathiwat",
"mueang nong khai",
"mueang nongbua lamphu",
"mueang nonthaburi",
"mueang pan",
"mueang pathum thani",
"mueang pattani",
"mueang phang nga",
"mueang phatthalung",
"mueang phayao",
"mueang phetchabun",
"mueang phetchaburi",
"mueang phichit",
"mueang phitsanulok",
"mueang phrae",
"mueang phuket",
"mueang prachinburi",
"mueang prachuap khiri khan",
"mueang ranong",
"mueang ratchaburi",
"mueang rayong",
"mueang roi et",
"mueang sa kaeo",
"mueang sakon nakhon",
"mueang samut prakan",
"mueang samut sakhon",
"mueang samut songkhram",
"mueang saraburi",
"mueang satun",
"mueang sing buri",
"mueang sisaket",
"mueang songkhla",
"mueang suang",
"mueang sukhothai",
"mueang suphanburi",
"mueang surat thani",
"mueang surin",
"mueang tak",
"mueang trang",
"mueang trat",
"mueang ubon ratchathani",
"mueang udon thani",
"mueang uthai thani",
"mueang uttaradit",
"mueang yala",
"mueang yang",
"mueang yasothon",
"na bon",
"na chaluai",
"na chueak",
"na di",
"na duang",
"na dun",
"na haeo",
"na kae",
"na khu",
"na klang",
"na mom",
"na mon",
"na muen",
"na noi",
"na pho",
"na tan",
"na thawi",
"na thom",
"na wa",
"na wang",
"na yai am",
"na yia",
"na yong",
"na yung",
"nakhon chai si",
"nakhon luang",
"nakhon thai",
"nam khun",
"nam kliang",
"nam nao",
"nam pat",
"nam phong",
"nam som",
"nam yuen",
"nang rong",
"ngao",
"nikhom kham soi",
"nikhom nam un",
"nikhom phatthana",
"noen kham",
"noen maprang",
"noen sa-nga",
"non daeng",
"non din daeng",
"non khun",
"non narai",
"non sa-at",
"non sang",
"non sila",
"non sung",
"non suwan",
"non thai",
"nong bua",
"nong bua daeng",
"nong bua rawe",
"nong bun mak",
"nong chang",
"nong chik",
"nong don",
"nong han",
"nong hi",
"nong hin",
"nong hong",
"nong khae",
"nong khayang",
"nong ki",
"nong kung si",
"nong mamong",
"nong muang",
"nong muang khai",
"nong na kham",
"nong phai",
"nong phok",
"nong prue",
"nong ruea",
"nong song hong",
"nong suea",
"nong sung",
"nong wua so",
"nong ya plong",
"nong ya sai",
"nong yai",
"nopphitam",
"nuea khlong",
"omkoi",
"ongkharak",
"pa bon",
"pa daet",
"pa mok",
"pa phayom",
"pa sang",
"pa tio",
"pai",
"pak chom",
"pak chong",
"pak khat",
"pak kret",
"pak phanang",
"pak phayun",
"pak phli",
"pak tho",
"pak thong chai",
"pakham",
"palian",
"panare",
"pang mapha",
"pang sila thong",
"pathio",
"pathum rat",
"pathum ratchawongsa",
"pha khao",
"phachi",
"phaisali",
"phak hai",
"phakdi chumphon",
"phan",
"phan thong",
"phana",
"phanat nikhom",
"phang khon",
"phanna nikhom",
"phanom",
"phanom dong rak",
"phanom phrai",
"phanom sarakham",
"phanom thuan",
"phato",
"phatthana nikhom",
"phaya mengrai",
"phayakkhaphum phisai",
"phayu",
"phayuha khiri",
"phen",
"phibun mangsahan",
"phibun rak",
"phichai",
"phimai",
"phipun",
"phlapphla chai",
"pho chai",
"pho prathap chang",
"pho sai",
"pho si suwan",
"pho tak",
"pho thale",
"pho thong",
"phon",
"phon charoen",
"phon na kaeo",
"phon phisai",
"phon sai",
"phon sawan",
"phon thong",
"phop phra",
"photharam",
"phra nakhon si ayutthaya",
"phra phrom",
"phra phutthabat",
"phra pradaeng",
"phra samut chedi",
"phra thong kham",
"phra yuen",
"phrai bueng",
"phran kratai",
"phrao",
"phrasaeng",
"phrom buri",
"phrom khiri",
"phrom phiram",
"phu kamyao",
"phu khiao",
"phu kradueng",
"phu luang",
"phu pha man",
"phu phan",
"phu phiang",
"phu ruea",
"phu sang",
"phu sing",
"phu wiang",
"phunphin",
"phutthaisong",
"phutthamonthon",
"pla pak",
"plaeng yao",
"plai phraya",
"pluak daeng",
"pong",
"pong nam ron",
"prachaksinlapakhom",
"prachantakham",
"prakhon chai",
"pran buri",
"prang ku",
"prasat",
"prathai",
"pua",
"pueai noi",
"ra-ngae",
"raman",
"ranot",
"rasi salai",
"ratchasan",
"ratsada",
"rattanaburi",
"rattanawapi",
"rattaphum",
"renu nakhon",
"ron phibun",
"rong kham",
"rong kwang",
"rueso",
"sa bot",
"saba yoi",
"sadao",
"sahatsakhan",
"sai buri",
"sai mun",
"sai ngam",
"sai noi",
"sai thong watthana",
"sai yok",
"sak lek",
"sakhrai",
"sam chai",
"sam chuk",
"sam khok",
"sam ngam",
"sam ngao",
"sam phran",
"sam roi yot",
"sam sung",
"samko",
"samoeng",
"samrong",
"samrong thap",
"san kamphaeng",
"san pa tong",
"san sai",
"sanam chai khet",
"sang khom",
"sangkha",
"sangkhla buri",
"sangkhom",
"sankhaburi",
"sanom",
"santi suk",
"sao hai",
"sap yai",
"sapphaya",
"saraphi",
"sathing phra",
"sattahip",
"satuek",
"sawaeng ha",
"sawang arom",
"sawang daen din",
"sawang wirawong",
"sawankhalok",
"sawi",
"seka",
"selaphum",
"sena",
"senangkhanikhom",
"si banphot",
"si bun rueang",
"si chiang mai",
"si chomphu",
"si maha phot",
"si mahosot",
"si mueang mai",
"si nakhon",
"si narong",
"si prachan",
"si racha",
"si rattana",
"si sakhon",
"si samrong",
"si satchanalai",
"si sawat",
"si somdet",
"si songkhram",
"si that",
"si thep",
"si wilai",
"sichon",
"sida",
"sikao",
"sikhio",
"sikhoraphum",
"sila lat",
"singhanakhon",
"sirindhorn",
"so phisai",
"soem ngam",
"soeng sang",
"soi dao",
"somdet",
"song",
"song dao",
"song khwae",
"song phi nong",
"sop moei",
"sop prap",
"srinagarindra",
"su-ngai kolok",
"su-ngai padi",
"suan phueng",
"suk samran",
"sukhirin",
"sung men",
"sung noen",
"suwannakhuha",
"suwannaphum",
"ta phraya",
"tak bai",
"tak fa",
"takhli",
"takua pa",
"takua thung",
"tamot",
"tan sum",
"tao ngoi",
"taphan hin",
"tha bo",
"tha chana",
"tha khantho",
"tha li",
"tha luang",
"tha mai",
"tha maka",
"tha muang",
"tha phae",
"tha pla",
"tha ruea",
"tha sae",
"tha sala",
"tha song yang",
"tha takiap",
"tha tako",
"tha tum",
"tha uthen",
"tha wang pha",
"tha wung",
"tha yang",
"thai charoen",
"thai mueang",
"thalang",
"tham phannara",
"than to",
"thanyaburi",
"thap khlo",
"thap put",
"thap sakae",
"thap than",
"that phanom",
"thawat buri",
"thep sathit",
"thepha",
"thepharak",
"thoen",
"thoeng",
"thong pha phum",
"thong saen khan",
"thung chang",
"thung fon",
"thung hua chang",
"thung khao luang",
"thung saliam",
"thung si udom",
"thung song",
"thung tako",
"thung wa",
"thung yai",
"thung yang daeng",
"trakan phuet phon",
"tron",
"u thong",
"ubolratana",
"umphang",
"uthai",
"uthumphon phisai",
"vibhavadi",
"wachirabarami",
"waeng",
"waeng noi",
"waeng yai",
"wan yai",
"wang chan",
"wang chao",
"wang chin",
"wang hin",
"wang muang",
"wang nam khiao",
"wang nam yen",
"wang noi",
"wang nuea",
"wang pong",
"wang sai phun",
"wang sam mo",
"wang saphung",
"wang sombun",
"wang thong",
"wang wiset",
"wang yang",
"wanon niwat",
"wapi pathum",
"warin chamrap",
"waritchaphum",
"wat bot",
"wat phleng",
"wat sing",
"watthana nakhon",
"wiang chai",
"wiang chiang rung",
"wiang haeng",
"wiang kaen",
"wiang kao",
"wiang nong long",
"wiang pa pao",
"wichian buri",
"wihan daeng",
"wiset chai chan",
"yaha",
"yan ta khao",
"yang chum noi",
"yang sisurat",
"yang talat",
"yarang",
"yaring",
"yi-ngo"
];
