module.exports = [
  "amnat charoen",
  "ang thong",
  "bangkok",
  "buri ram",
  "chachoengsao",
  "chai nat",
  "chaiyaphum",
  "chanthaburi",
  "chiang mai",
  "chiang rai",
  "chon buri",
  "chumphon",
  "kalasin",
  "kamphaeng phet",
  "kanchanaburi",
  "khon kaen",
  "krabi",
  "lampang",
  "lamphun",
  "loei",
  "lop buri",
  "mae hong son",
  "maha sarakham",
  "mukdahan",
  "nakhon nayok",
  "nakhon pathom",
  "nakhon phanom",
  "nakhon ratchasima",
  "nakhon sawan",
  "nakhon si thammarat",
  "nan",
  "narathiwat",
  "nong bua lam phu",
  "nong khai",
  "nonthaburi",
  "pathum thani",
  "pattani",
  "phangnga",
  "phatthalung (songkhla lake)",
  "phatthalung",
  "phayao",
  "phetchabun",
  "phetchaburi",
  "phichit",
  "phitsanulok",
  "phra nakhon si ayutthaya",
  "phrae",
  "phuket",
  "prachin buri",
  "prachuap khiri khan",
  "ranong",
  "ratchaburi",
  "rayong",
  "roi et",
  "sa kaeo",
  "sakon nakhon",
  "samut prakan",
  "samut sakhon",
  "samut songkhram",
  "saraburi",
  "satun",
  "si sa ket",
  "sing buri",
  "songkhla (songkhla lake)",
  "songkhla",
  "sukhothai",
  "suphan buri",
  "surat thani",
  "surin",
  "tak",
  "trang",
  "trat",
  "ubon ratchathani",
  "udon thani",
  "uthai thani",
  "uttaradit",
  "yala",
  "yasothon"
];